### ISSUE TITLE
Display connection name in rabbit admin

### ISSUE THREAD

**Issue by rlavolee** [hnaderi/lepus#209]
I've seen that we can add a connection name which is useful to resolve who's who in the Rabbit Admin.

However I don't know if it's a mistake or by choice but to display connection name under its ip address in Rabbit `Connection` listing,  `connection_name` should be at root level of `FieldTable`. Currently it's in `capabilities` level as shown below.

```scala
    FieldTable(
      ShortString("product") -> ShortString("Lepus"),
      ShortString("version") -> ShortString(BuildInfo.version),
      ShortString("platform") -> ShortString("scala"),
      ShortString("scala-version") -> ShortString(BuildInfo.scalaVersion),
      ShortString("capabilities") -> FieldTable(
        ShortString("publisher_confirms") -> true,
        ShortString("authentication_failure_close") -> true,
        ShortString("consumer_cancel_notify") -> true,
        ShortString("basic.nack") -> true,
        ShortString("connection.blocked") -> true
      ).updated(ShortString("connection_name"), connectionName)
    )
```  

Are you interested in a fix ? :)

**Comment by hnaderi** [comment]
It's a mistake for sure! :sweat_smile: 
It supposed to be after the next parenthesis.

**Comment by hnaderi** [comment]
Thank you! I just pushed the bug fix.
